# Generated by Django 2.0.2 on 2018-02-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('established', models.DateField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images')),
            ],
        ),
    ]
